environment: staging
version: "1.0.0-staging"

# Database Configuration
database:
  host: db-staging
  port: 5432
  name: orchestratex_staging
  user: admin

# API Configuration
api:
  port: 8000
  environment: staging
  log_level: info

# Security Configuration
security:
  jwt_secret: "staging-secret-key-change-in-production"
  password_salt_rounds: 12
  mfa_enabled: true

# Monitoring Configuration
monitoring:
  enabled: true
  prometheus:
    port: 9090
  grafana:
    port: 3000
  elk:
    enabled: true
    port: 5601

# Content Management
content:
  storage:
    type: cloud
    provider: aws
    bucket: orchestratex-staging-content
  replication:
    enabled: true
    regions: ["us-east-1", "us-west-2"]

# Quantum Computing
quantum:
  provider: aws-braket
  simulation: false
  max_qubits: 32

# AI Configuration
ai:
  model_path: /models/staging
  cache_enabled: true
  cache_size: 16GB

# Deployment Settings
deployment:
  environment: staging
  auto_deploy: true
  rollbacks_enabled: true
  canary_release: true
