apiVersion: security.orchestratex.com/v1
kind: SecurityAuditConfig
metadata:
  name: orchestratex-security-audit
  namespace: orchestratex
spec:
  audit:
    schedule:
      interval: "1d"
      timezone: "UTC"
      start_time: "00:00"
    scope:
      - type: code
        path: "src/**"
        exclusions:
          - "**/test/**"
          - "**/docs/**"
          - "**/examples/**"
      - type: infrastructure
        providers:
          - aws
          - gcp
          - azure
      - type: network
        protocols:
          - tcp
          - udp
        ports:
          - 80
          - 443
          - 22
      - type: authentication
        methods:
          - password
          - mfa
          - oauth
      - type: authorization
        policies:
          - rbac
          - abac
          - pbac
      - type: data_protection
        encryption:
          algorithms:
            - kyber
            - dilithium
            - aes-gcm
          key_sizes:
            - 256
            - 384
            - 512
      - type: monitoring
        metrics:
          - cpu
          - memory
          - network
          - disk
        thresholds:
          cpu: 85
          memory: 90
          network: 95
          disk: 95
    rules:
      code:
        - name: no_hardcoded_secrets
          description: "No hardcoded secrets in code"
          severity: critical
          pattern: "(?i)(password|secret|token|key)\s*=?\s*['\"]"
        - name: no_unsafe_operations
          description: "No unsafe operations in code"
          severity: warning
          pattern: "eval\(|exec\(|os\.system\(|subprocess\.Popen\(""
      infrastructure:
        - name: no_public_ssh
          description: "No public SSH access"
          severity: critical
          pattern: "22\s*allow"
        - name: no_root_access
          description: "No root access allowed"
          severity: critical
          pattern: "root\s*allow"
      network:
        - name: no_unencrypted_traffic
          description: "No unencrypted traffic allowed"
          severity: critical
          pattern: "tcp\s*80"
        - name: no_unrestricted_access
          description: "No unrestricted access allowed"
          severity: warning
          pattern: "0\.0\.0\.0/0"
      authentication:
        - name: require_mfa
          description: "MFA required for all users"
          severity: critical
          pattern: "mfa\s*disabled"
        - name: strong_passwords
          description: "Strong password policy required"
          severity: warning
          pattern: "password_length\s*<\s*12"
      authorization:
        - name: least_privilege
          description: "Least privilege principle enforced"
          severity: critical
          pattern: "admin\s*role"
        - name: no_wildcard_permissions
          description: "No wildcard permissions allowed"
          severity: warning
          pattern: "\*\s*allow"
      data_protection:
        - name: require_encryption
          description: "Encryption required for all data"
          severity: critical
          pattern: "encryption\s*disabled"
        - name: strong_encryption
          description: "Strong encryption algorithms required"
          severity: warning
          pattern: "aes-128"
      monitoring:
        - name: require_alerting
          description: "Alerting required for critical metrics"
          severity: critical
          pattern: "alert\s*disabled"
        - name: require_logging
          description: "Logging required for all operations"
          severity: warning
          pattern: "logging\s*disabled"
    metrics:
      code:
        - name: code_coverage
          description: "Code coverage percentage"
          unit: "%"
          target: 90
          threshold:
            warning: 85
            critical: 80
        - name: code_quality
          description: "Code quality score"
          unit: "score"
          target: 9
          threshold:
            warning: 7
            critical: 5
      infrastructure:
        - name: infra_compliance
          description: "Infrastructure compliance score"
          unit: "%"
          target: 100
          threshold:
            warning: 95
            critical: 90
        - name: infra_security
          description: "Infrastructure security score"
          unit: "%"
          target: 100
          threshold:
            warning: 95
            critical: 90
      network:
        - name: network_security
          description: "Network security score"
          unit: "%"
          target: 100
          threshold:
            warning: 95
            critical: 90
        - name: network_performance
          description: "Network performance score"
          unit: "ms"
          target: 100
          threshold:
            warning: 200
            critical: 500
      authentication:
        - name: auth_strength
          description: "Authentication strength score"
          unit: "%"
          target: 100
          threshold:
            warning: 95
            critical: 90
        - name: auth_coverage
          description: "Authentication coverage percentage"
          unit: "%"
          target: 100
          threshold:
            warning: 95
            critical: 90
      authorization:
        - name: authz_coverage
          description: "Authorization coverage percentage"
          unit: "%"
          target: 100
          threshold:
            warning: 95
            critical: 90
        - name: authz_compliance
          description: "Authorization compliance score"
          unit: "%"
          target: 100
          threshold:
            warning: 95
            critical: 90
      data_protection:
        - name: encryption_coverage
          description: "Encryption coverage percentage"
          unit: "%"
          target: 100
          threshold:
            warning: 95
            critical: 90
        - name: data_protection_score
          description: "Data protection score"
          unit: "%"
          target: 100
          threshold:
            warning: 95
            critical: 90
      monitoring:
        - name: monitoring_coverage
          description: "Monitoring coverage percentage"
          unit: "%"
          target: 100
          threshold:
            warning: 95
            critical: 90
        - name: alert_coverage
          description: "Alert coverage percentage"
          unit: "%"
          target: 100
          threshold:
            warning: 95
            critical: 90
    notifications:
      enabled: true
      channels:
        - type: slack
          webhook: ${SLACK_WEBHOOK}
          channel: "#security"
          severity:
            warning: true
            critical: true
        - type: email
          recipients:
            - "security@orchestratex.com"
            - "ops@orchestratex.com"
          severity:
            warning: true
            critical: true
        - type: pagerduty
          service_key: ${PAGERDUTY_SERVICE_KEY}
          severity:
            warning: false
            critical: true
    compliance:
      enabled: true
      standards:
        - name: NIST 800-53
          requirements:
            - "AU-2 Audit Events"
            - "AU-3 Content of Audit Records"
            - "AU-4 Audit Storage"
            - "AU-6 Audit Review"
        - name: ISO 27001
          requirements:
            - "A.12.4.1 Audit trails"
            - "A.12.4.2 Protection of audit trails"
            - "A.12.4.3 Review of audit trails"
        - name: GDPR
          requirements:
            - "Article 30 - Record of processing activities"
            - "Article 32 - Security of processing"
            - "Article 33 - Notification of a personal data breach to the supervisory authority"
      exceptions:
        - name: development_environment
          description: "Development environment exception"
          conditions:
            - environment: "dev"
            - threshold: "warning"
        - name: experimental_code
          description: "Experimental code exception"
          conditions:
            - tag: "experimental"
            - threshold: "warning"
    reporting:
      enabled: true
      format: "html"
      output_dir: "audit_reports"
      include:
        - "audit_summary.html"
        - "audit_details.html"
        - "audit_metrics.html"
        - "audit_recommendations.html"
      exclude:
        - "**/test_*.html"
        - "**/debug_*.html"
    audit_trail:
      enabled: true
      retention:
        days: 365
        compression: true
        encryption: true
      storage:
        type: s3
        bucket: "orchestratex-audit-trail"
        region: "us-east-1"
    alerting:
      enabled: true
      rules:
        - name: critical_issues
          description: "Critical security issues detected"
          severity: critical
          threshold: 1
          notification_channels:
            - type: slack
              webhook: ${SLACK_WEBHOOK}
              channel: "#alerts"
            - type: pagerduty
              service_key: ${PAGERDUTY_SERVICE_KEY}
        - name: high_risk_changes
          description: "High risk configuration changes detected"
          severity: warning
          threshold: 5
          notification_channels:
            - type: slack
              webhook: ${SLACK_WEBHOOK}
              channel: "#security"
            - type: email
              recipients:
                - "security@orchestratex.com"
    enforcement:
      enabled: true
      mode: strict
      exceptions:
        - name: development
          description: "Development environment exception"
          conditions:
            - environment: "dev"
            - threshold: "warning"
        - name: experimental
          description: "Experimental feature exception"
          conditions:
            - tag: "experimental"
            - threshold: "warning"
    monitoring:
      enabled: true
      interval: "1h"
      metrics:
        - name: audit_coverage
          description: "Audit coverage percentage"
          unit: "%"
          aggregation: "avg"
        - name: audit_compliance
          description: "Audit compliance score"
          unit: "%"
          aggregation: "avg"
      alerts:
        - name: low_coverage
          description: "Low audit coverage"
          severity: warning
          threshold: 85
          notification_channels:
            - type: slack
              webhook: ${SLACK_WEBHOOK}
              channel: "#alerts"
            - type: email
              recipients:
                - "security@orchestratex.com"
        - name: non_compliance
          description: "Non-compliance detected"
          severity: critical
          threshold: 90
          notification_channels:
            - type: slack
              webhook: ${SLACK_WEBHOOK}
              channel: "#alerts"
            - type: pagerduty
              service_key: ${PAGERDUTY_SERVICE_KEY}
    documentation:
      enabled: true
      format: "markdown"
      output_dir: "docs/security"
      include:
        - "audit_procedure.md"
        - "compliance_guide.md"
        - "remediation_procedures.md"
      exclude:
        - "**/draft_*.md"
        - "**/temp_*.md"
    remediation:
      enabled: true
      procedures:
        - name: critical_vulnerability
          description: "Critical vulnerability remediation"
          steps:
            - "Isolate affected systems"
            - "Apply security patches"
            - "Validate fixes"
            - "Document changes"
        - name: compliance_issue
          description: "Compliance issue remediation"
          steps:
            - "Identify non-compliant areas"
            - "Implement fixes"
            - "Verify compliance"
            - "Update documentation"
      escalation:
        - name: critical
          description: "Critical issue escalation"
          conditions:
            - severity: "critical"
          actions:
            - "Notify security team"
            - "Escalate to CISO"
            - "Activate incident response"
        - name: high
          description: "High severity issue escalation"
          conditions:
            - severity: "high"
          actions:
            - "Notify security team"
            - "Escalate to manager"
            - "Schedule remediation"
    audit_log:
      enabled: true
      format: "json"
      retention:
        days: 365
        compression: true
        encryption: true
      storage:
        type: s3
        bucket: "orchestratex-audit-logs"
        region: "us-east-1"
    alert_log:
      enabled: true
      format: "json"
      retention:
        days: 365
        compression: true
        encryption: true
      storage:
        type: s3
        bucket: "orchestratex-alert-logs"
        region: "us-east-1"
    compliance_log:
      enabled: true
      format: "json"
      retention:
        days: 365
        compression: true
        encryption: true
      storage:
        type: s3
        bucket: "orchestratex-compliance-logs"
        region: "us-east-1"
