apiVersion: v1
kind: Service
metadata:
  name: orchestratex
  namespace: orchestratex
  labels:
    app: orchestratex
    component: api
spec:
  selector:
    app: orchestratex
    component: api
  ports:
    - name: http
      port: 8000
      targetPort: 8000
  type: ClusterIP

---

apiVersion: v1
kind: Service
metadata:
  name: orchestratex-external
  namespace: orchestratex
  labels:
    app: orchestratex
    component: api
spec:
  selector:
    app: orchestratex
    component: api
  ports:
    - name: http
      port: 80
      targetPort: 8000
  type: LoadBalancer
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: nlb
    service.beta.kubernetes.io/aws-load-balancer-internal: "true"
