apiVersion: v1
kind: ConfigMap
metadata:
  name: gcp-config
  namespace: orchestratex
data:
  project_id: orchestratex-project
  region: us-central1
  zone: us-central1-a
  cluster_name: orchestratex-cluster
  node_pool_name: default-pool
  machine_type: n1-standard-4
  disk_size_gb: "100"
  min_nodes: "3"
  max_nodes: "10"

---

apiVersion: v1
kind: Secret
metadata:
  name: gcp-credentials
  namespace: orchestratex
type: Opaque
data:
  # Base64 encoded service account key
  credentials: ""

---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: orchestratex-sa
  namespace: orchestratex
secrets:
- name: gcp-credentials

---

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: gcp-role
  namespace: orchestratex
rules:
- apiGroups: ["cloud.google.com"]
  resources: ["*"]
  verbs: ["*"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: gcp-role-binding
  namespace: orchestratex
subjects:
- kind: ServiceAccount
  name: orchestratex-sa
  namespace: orchestratex
roleRef:
  kind: Role
  name: gcp-role
  apiGroup: rbac.authorization.k8s.io
