apiVersion: v1
kind: ConfigMap
metadata:
  name: registry-config
  namespace: orchestratex
data:
  registry_url: gcr.io/orchestratex-project
  repository: orchestratex
  tag: latest

---

apiVersion: v1
kind: Secret
metadata:
  name: registry-credentials
  namespace: orchestratex
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: ""

---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: registry-push
  namespace: orchestratex
secrets:
- name: registry-credentials

---

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: registry-role
  namespace: orchestratex
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "list"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: registry-role-binding
  namespace: orchestratex
subjects:
- kind: ServiceAccount
  name: registry-push
  namespace: orchestratex
roleRef:
  kind: Role
  name: registry-role
  apiGroup: rbac.authorization.k8s.io
