apiVersion: testing.orchestratex.com/v1
kind: TestConfig
metadata:
  name: orchestratex-testing
  namespace: orchestratex
spec:
  test_suites:
    - name: quantum_operations
      description: "Quantum operation tests"
      tests:
        - name: circuit_creation
          type: unit
          description: "Test quantum circuit creation"
          assertions:
            - circuit_depth: 100
            - qubit_count: 16
            - gate_count: 1000
          thresholds:
            success_rate: 99.9
            execution_time: 1000
        - name: state_preparation
          type: unit
          description: "Test quantum state preparation"
          assertions:
            - state_validity: true
            - amplitude_error: 0.001
            - phase_error: 0.001
          thresholds:
            success_rate: 99.9
            execution_time: 500
        - name: measurement
          type: unit
          description: "Test quantum measurement"
          assertions:
            - measurement_error: 0.01
            - sample_variance: 0.001
          thresholds:
            success_rate: 99.9
            execution_time: 200
    - name: api_endpoints
      description: "API endpoint tests"
      tests:
        - name: quantum_execute
          type: integration
          description: "Test quantum execution endpoint"
          assertions:
            - status_code: 200
            - response_time: 500
            - error_rate: 0.01
          thresholds:
            success_rate: 99.9
            execution_time: 1000
        - name: state_query
          type: integration
          description: "Test quantum state query"
          assertions:
            - status_code: 200
            - response_time: 200
            - data_validity: true
          thresholds:
            success_rate: 99.9
            execution_time: 500
        - name: circuit_optimize
          type: integration
          description: "Test circuit optimization"
          assertions:
            - status_code: 200
            - optimization_factor: 0.8
            - execution_time: 1000
          thresholds:
            success_rate: 99.9
            execution_time: 2000
    - name: performance
      description: "Performance tests"
      tests:
        - name: circuit_throughput
          type: performance
          description: "Test circuit execution throughput"
          assertions:
            - throughput: 1000
            - latency: 500
            - error_rate: 0.01
          thresholds:
            success_rate: 99.9
            execution_time: 3000
        - name: state_processing
          type: performance
          description: "Test state processing"
          assertions:
            - processing_rate: 500
            - memory_usage: 1000
            - cpu_usage: 80
          thresholds:
            success_rate: 99.9
            execution_time: 2000
        - name: api_load
          type: performance
          description: "Test API load handling"
          assertions:
            - max_requests: 1000
            - response_time: 1000
            - error_rate: 0.01
          thresholds:
            success_rate: 99.9
            execution_time: 5000
  test_environment:
    quantum:
      backend: "qiskit"
      provider: "ibm"
      qubits: 16
      shots: 1024
    api:
      endpoint: "http://api.orchestratex.svc.cluster.local"
      timeout: 3000
      retries: 3
    database:
      type: "postgresql"
      host: "db.orchestratex.svc.cluster.local"
      port: 5432
      pool_size: 10
  test_data:
    generation:
      enabled: true
      types:
        - quantum_circuit
        - quantum_state
        - api_request
      parameters:
        circuit_depth: [50, 100, 200]
        qubit_count: [8, 16, 32]
        request_size: [100, 500, 1000]
    storage:
      type: "s3"
      bucket: "orchestratex-test-data"
      region: "us-east-1"
      retention:
        days: 30
        compression: true
        encryption: true
  test_execution:
    parallel:
      enabled: true
      max_workers: 10
      batch_size: 100
    retry:
      enabled: true
      max_attempts: 3
      delay: "1s"
    timeout:
      unit_tests: "5s"
      integration_tests: "30s"
      performance_tests: "60s"
  test_reporting:
    enabled: true
    format: "html"
    output_dir: "test_reports"
    include:
      - "test_summary.html"
      - "test_details.html"
      - "performance_metrics.html"
      - "coverage_report.html"
    exclude:
      - "**/draft_*.html"
      - "**/debug_*.html"
  test_metrics:
    enabled: true
    collection:
      interval: "1s"
      retention:
        days: 30
        compression: true
        encryption: true
    providers:
      - name: prometheus
        url: "http://prometheus.orchestratex.svc.cluster.local:9090"
        scrape_interval: "1s"
      - name: grafana
        url: "http://grafana.orchestratex.svc.cluster.local:3000"
        dashboard_refresh: "5s"
    metrics:
      - name: test_success_rate
        description: "Test success rate"
        unit: "%"
        aggregation: "avg"
        threshold:
          warning: 95
          critical: 90
      - name: test_execution_time
        description: "Test execution time"
        unit: "ms"
        aggregation: "avg"
        threshold:
          warning: 1000
          critical: 2000
      - name: test_coverage
        description: "Test coverage"
        unit: "%"
        aggregation: "avg"
        threshold:
          warning: 85
          critical: 80
  test_alerting:
    enabled: true
    rules:
      - name: test_failure
        description: "Test failures detected"
        severity: critical
        threshold: 1
        notification_channels:
          - type: slack
            webhook: ${SLACK_WEBHOOK}
            channel: "#alerts"
          - type: pagerduty
            service_key: ${PAGERDUTY_SERVICE_KEY}
      - name: low_coverage
        description: "Low test coverage"
        severity: warning
        threshold: 85
        notification_channels:
          - type: slack
            webhook: ${SLACK_WEBHOOK}
            channel: "#testing"
          - type: email
            recipients:
              - "dev@orchestratex.com"
    notification_channels:
      slack:
        webhook: ${SLACK_WEBHOOK}
        channel: "#testing"
        severity:
          warning: true
          critical: true
      email:
        recipients:
          - "dev@orchestratex.com"
          - "ops@orchestratex.com"
        severity:
          warning: true
          critical: true
      pagerduty:
        service_key: ${PAGERDUTY_SERVICE_KEY}
        severity:
          warning: false
          critical: true
  test_compliance:
    enabled: true
    standards:
      - name: ISO 29119
        requirements:
          - "Test planning"
          - "Test design"
          - "Test execution"
          - "Test reporting"
      - name: IEEE 829
        requirements:
          - "Test plan"
          - "Test summary"
          - "Test results"
          - "Test logs"
    exceptions:
      - name: development_environment
        description: "Development environment exception"
        conditions:
          - environment: "dev"
          - threshold: "warning"
      - name: experimental_code
        description: "Experimental code exception"
        conditions:
          - tag: "experimental"
          - threshold: "warning"
  test_audit:
    enabled: true
    retention:
      days: 365
      compression: true
      encryption: true
    storage:
      type: "s3"
      bucket: "orchestratex-test-audit"
      region: "us-east-1"
  test_log:
    enabled: true
    format: "json"
    level: "info"
    retention:
      days: 30
      compression: true
      encryption: true
    storage:
      type: "s3"
      bucket: "orchestratex-test-logs"
      region: "us-east-1"
  test_validation:
    enabled: true
    rules:
      - name: quantum_state_validity
        description: "Quantum state validation"
        checks:
          - normalization
          - probability_distribution
          - entanglement
      - name: circuit_validity
        description: "Quantum circuit validation"
        checks:
          - gate_sequence
          - qubit_count
          - measurement_points
      - name: api_response_validity
        description: "API response validation"
        checks:
          - schema_validation
          - data_consistency
          - error_handling
  test_security:
    enabled: true
    checks:
      - authentication
      - authorization
      - encryption
      - data_protection
    compliance:
      - name: OWASP
        requirements:
          - "Authentication"
          - "Authorization"
          - "Data Protection"
          - "Cryptography"
      - name: NIST
        requirements:
          - "Access Control"
          - "Audit and Accountability"
          - "System and Communications Protection"
  test_performance:
    enabled: true
    metrics:
      - name: throughput
        unit: "requests/second"
        threshold:
          warning: 1000
          critical: 500
      - name: latency
        unit: "ms"
        threshold:
          warning: 500
          critical: 1000
      - name: resource_usage
        unit: "%"
        threshold:
          warning: 85
          critical: 90
    load_tests:
      - name: quantum_load
        description: "Quantum operation load test"
        parameters:
          users: 100
          ramp_up: "10s"
          duration: "1m"
          assertions:
            - success_rate: 99.9
            - response_time: 1000
      - name: api_load
        description: "API endpoint load test"
        parameters:
          users: 500
          ramp_up: "30s"
          duration: "5m"
          assertions:
            - success_rate: 99.9
            - response_time: 500
  test_coverage:
    enabled: true
    targets:
      - name: quantum_core
        path: "quantum/core"
        threshold:
          statement: 95
          branch: 85
          function: 90
          line: 95
      - name: quantum_ml
        path: "quantum/ml"
        threshold:
          statement: 90
          branch: 80
          function: 85
          line: 90
      - name: quantum_circuit
        path: "quantum/circuit"
        threshold:
          statement: 95
          branch: 90
          function: 95
          line: 95
      - name: quantum_state
        path: "quantum/state"
        threshold:
          statement: 90
          branch: 85
          function: 90
          line: 90
    exclusions:
      - "**/test_*.py"
      - "**/__init__.py"
      - "**/setup.py"
      - "**/migrations/**"
      - "**/docs/**"
      - "**/examples/**"
