apiVersion: audit.orchestratex.com/v1
kind: ComplianceReportConfig
metadata:
  name: orchestratex-compliance
  namespace: orchestratex
spec:
  standards:
    - name: ISO 27001
      description: "Information security management"
      requirements:
        - name: A.5.1.1
          description: "Information security policies"
          category: "Security policy"
          status: "implemented"
          evidence:
            - type: "document"
              path: "policies/security_policy.pdf"
            - type: "audit"
              reference: "daily_audit_001"
        - name: A.5.1.2
          description: "Management commitment"
          category: "Security policy"
          status: "implemented"
          evidence:
            - type: "document"
              path: "policies/management_commitment.pdf"
            - type: "audit"
              reference: "weekly_audit_001"
        - name: A.5.2.1
          description: "Information security roles and responsibilities"
          category: "Organization of information security"
          status: "implemented"
          evidence:
            - type: "document"
              path: "roles/security_roles.pdf"
            - type: "audit"
              reference: "monthly_audit_001"
        - name: A.5.2.2
          description: "Information security responsibilities"
          category: "Organization of information security"
          status: "implemented"
          evidence:
            - type: "document"
              path: "roles/security_responsibilities.pdf"
            - type: "audit"
              reference: "quarterly_audit_001"
        - name: A.6.1.1
          description: "Human resource security"
          category: "Human resource security"
          status: "implemented"
          evidence:
            - type: "document"
              path: "hr/security_hr_policy.pdf"
            - type: "audit"
              reference: "annual_audit_001"
    - name: NIST 800-53
      description: "Security and privacy controls"
      requirements:
        - name: AC-1
          description: "Access Control Policy and Procedures"
          category: "Access Control"
          status: "implemented"
          evidence:
            - type: "document"
              path: "controls/access_control_policy.pdf"
            - type: "audit"
              reference: "daily_audit_002"
        - name: AC-2
          description: "Account Management"
          category: "Access Control"
          status: "implemented"
          evidence:
            - type: "document"
              path: "controls/account_management.pdf"
            - type: "audit"
              reference: "weekly_audit_002"
        - name: AC-3
          description: "Access Enforcement"
          category: "Access Control"
          status: "implemented"
          evidence:
            - type: "document"
              path: "controls/access_enforcement.pdf"
            - type: "audit"
              reference: "monthly_audit_002"
        - name: AC-4
          description: "Information Flow Enforcement"
          category: "Access Control"
          status: "implemented"
          evidence:
            - type: "document"
              path: "controls/information_flow.pdf"
            - type: "audit"
              reference: "quarterly_audit_002"
        - name: AC-5
          description: "Security Assessment and Authorization"
          category: "Access Control"
          status: "implemented"
          evidence:
            - type: "document"
              path: "controls/authorization.pdf"
            - type: "audit"
              reference: "annual_audit_002"
    - name: GDPR
      description: "General Data Protection Regulation"
      requirements:
        - name: Article 5
          description: "Principles of personal data processing"
          category: "Data Protection"
          status: "implemented"
          evidence:
            - type: "document"
              path: "gdpr/principles.pdf"
            - type: "audit"
              reference: "daily_audit_003"
        - name: Article 25
          description: "Data protection by design and by default"
          category: "Data Protection"
          status: "implemented"
          evidence:
            - type: "document"
              path: "gdpr/design_protection.pdf"
            - type: "audit"
              reference: "weekly_audit_003"
        - name: Article 32
          description: "Security of processing"
          category: "Data Protection"
          status: "implemented"
          evidence:
            - type: "document"
              path: "gdpr/security_processing.pdf"
            - type: "audit"
              reference: "monthly_audit_003"
        - name: Article 35
          description: "Data protection impact assessment"
          category: "Data Protection"
          status: "implemented"
          evidence:
            - type: "document"
              path: "gdpr/impact_assessment.pdf"
            - type: "audit"
              reference: "quarterly_audit_003"
        - name: Article 36
          description: "Prior consultation"
          category: "Data Protection"
          status: "implemented"
          evidence:
            - type: "document"
              path: "gdpr/consultation.pdf"
            - type: "audit"
              reference: "annual_audit_003"
  reports:
    - name: daily_report
      description: "Daily compliance report"
      schedule: "0 0 * * *"
      timezone: "UTC"
      format: "pdf"
      recipients:
        - "security@orchestratex.com"
        - "audit@orchestratex.com"
      sections:
        - name: "summary"
          description: "Compliance summary"
          include:
            - "standards"
            - "requirements"
            - "status"
            - "alerts"
        - name: "details"
          description: "Detailed compliance information"
          include:
            - "evidence"
            - "audit_results"
            - "metrics"
            - "coverage"
    - name: weekly_report
      description: "Weekly compliance report"
      schedule: "0 0 * * 0"
      timezone: "UTC"
      format: "pdf"
      recipients:
        - "security@orchestratex.com"
        - "audit@orchestratex.com"
        - "compliance@orchestratex.com"
      sections:
        - name: "summary"
          description: "Compliance summary"
          include:
            - "standards"
            - "requirements"
            - "status"
            - "alerts"
        - name: "details"
          description: "Detailed compliance information"
          include:
            - "evidence"
            - "audit_results"
            - "metrics"
            - "coverage"
    - name: monthly_report
      description: "Monthly compliance report"
      schedule: "0 0 1 * *"
      timezone: "UTC"
      format: "pdf"
      recipients:
        - "security@orchestratex.com"
        - "audit@orchestratex.com"
        - "compliance@orchestratex.com"
        - "executive@orchestratex.com"
      sections:
        - name: "summary"
          description: "Compliance summary"
          include:
            - "standards"
            - "requirements"
            - "status"
            - "alerts"
        - name: "details"
          description: "Detailed compliance information"
          include:
            - "evidence"
            - "audit_results"
            - "metrics"
            - "coverage"
  metrics:
    enabled: true
    collection:
      interval: "1h"
      retention:
        days: 30
        compression: true
        encryption: true
    providers:
      - name: prometheus
        url: "http://prometheus.orchestratex.svc.cluster.local:9090"
        scrape_interval: "15s"
      - name: grafana
        url: "http://grafana.orchestratex.svc.cluster.local:3000"
        dashboard_refresh: "30s"
    metrics:
      - name: compliance_score
        description: "Compliance score"
        unit: "%"
        aggregation: "avg"
        threshold:
          warning: 90
          critical: 85
      - name: requirement_coverage
        description: "Requirement coverage"
        unit: "%"
        aggregation: "avg"
        threshold:
          warning: 95
          critical: 90
      - name: evidence_validity
        description: "Evidence validity"
        unit: "%"
        aggregation: "avg"
        threshold:
          warning: 95
          critical: 90
  notifications:
    enabled: true
    channels:
      - type: slack
        webhook: ${SLACK_WEBHOOK}
        channel: "#compliance"
        severity:
          warning: true
          critical: true
      - type: email
        recipients:
          - "security@orchestratex.com"
          - "audit@orchestratex.com"
          - "compliance@orchestratex.com"
        severity:
          warning: true
          critical: true
      - type: pagerduty
        service_key: ${PAGERDUTY_SERVICE_KEY}
        severity:
          warning: false
          critical: true
  audit:
    enabled: true
    retention:
      days: 365
      compression: true
      encryption: true
    storage:
      type: "s3"
      bucket: "orchestratex-compliance-reports"
      region: "us-east-1"
  logging:
    enabled: true
    format: "json"
    level: "info"
    retention:
      days: 30
      compression: true
      encryption: true
    storage:
      type: "s3"
      bucket: "orchestratex-compliance-logs"
      region: "us-east-1"
  validation:
    enabled: true
    rules:
      - name: requirement_validation
        description: "Requirement validation"
        checks:
          - presence_check
          - status_check
          - evidence_check
      - name: evidence_validation
        description: "Evidence validation"
        checks:
          - existence_check
          - validity_check
          - accessibility_check
      - name: report_validation
        description: "Report validation"
        checks:
          - format_check
          - content_check
          - distribution_check
  security:
    enabled: true
    checks:
      - report_security
      - evidence_security
      - notification_security
      - storage_security
    compliance:
      - name: OWASP
        requirements:
          - "Authentication"
          - "Authorization"
          - "Data Protection"
          - "Cryptography"
      - name: NIST
        requirements:
          - "Access Control"
          - "Audit and Accountability"
          - "System and Communications Protection"
  performance:
    enabled: true
    metrics:
      - name: report_generation_time
        unit: "s"
        threshold:
          warning: 300
          critical: 600
      - name: report_distribution_time
        unit: "s"
        threshold:
          warning: 60
          critical: 120
      - name: report_error_rate
        unit: "%"
        threshold:
          warning: 1
          critical: 5
    load_tests:
      - name: report_load
        description: "Report load test"
        parameters:
          reports: 100
          duration: "1h"
          concurrency: 10
        assertions:
          - success_rate: 99.9
          - response_time: 300
          - throughput: 10
      - name: distribution_load
        description: "Distribution load test"
        parameters:
          recipients: 1000
          duration: "24h"
          concurrency: 50
        assertions:
          - success_rate: 99.9
          - response_time: 60
          - throughput: 5
  coverage:
    enabled: true
    targets:
      - name: compliance_coverage
        description: "Compliance coverage"
        threshold:
          standards: 95
          requirements: 90
          evidence: 95
      - name: report_coverage
        description: "Report coverage"
        threshold:
          sections: 95
          metrics: 90
          alerts: 95
      - name: validation_coverage
        description: "Validation coverage"
        threshold:
          checks: 95
          rules: 90
          procedures: 95
    exclusions:
      - "**/test_*.pdf"
      - "**/__init__.pdf"
      - "**/examples/**"
      - "**/templates/**"
