environment: production
version: "1.0.0-prod"

# Database Configuration
database:
  host: db-prod
  port: 5432
  name: orchestratex_prod
  user: admin
  replicas: 3

# API Configuration
api:
  port: 8000
  environment: production
  log_level: warn
  rate_limit:
    enabled: true
    max_requests: 1000
    window: 60

# Security Configuration
security:
  jwt_secret: "prod-secret-key-change-in-production"
  password_salt_rounds: 14
  mfa_enabled: true
  rbac:
    enabled: true
    strict_mode: true
  acl:
    enabled: true
    audit_enabled: true

# Monitoring Configuration
monitoring:
  enabled: true
  prometheus:
    port: 9090
    retention: 30d
  grafana:
    port: 3000
    dashboards:
      - system
      - ai_performance
      - quantum_metrics
  elk:
    enabled: true
    port: 5601
    retention: 90d

# Content Management
content:
  storage:
    type: hybrid
    providers:
      - aws
      - gcp
    buckets:
      aws: orchestratex-prod-content
      gcp: orchestratex-prod-content
  replication:
    enabled: true
    regions:
      - "us-east-1"
      - "us-west-2"
      - "eu-central-1"

# Quantum Computing
quantum:
  provider: multi-cloud
  providers:
    - aws-braket
    - ibm-quantum
    - google-quantum
  simulation: false
  max_qubits: 64

# AI Configuration
ai:
  model_path: /models/prod
  cache_enabled: true
  cache_size: 32GB
  model_versioning: true

# Deployment Settings
deployment:
  environment: production
  auto_deploy: false
  rollbacks_enabled: true
  canary_release: true
  blue_green: true
  auto_scaling:
    enabled: true
    min_replicas: 2
    max_replicas: 10
