security:
  rbac:
    roles:
      - admin: [create, delete, override]
      - developer: [write, execute]
      - auditor: [read, monitor]
  
  data_protection:
    encryption:
      at_rest: aes-256
      in_transit: tls1.3
    anonymization:
      techniques:
        - differential_privacy
        - k-anonymity
  
  compliance:
    standards:
      - GDPR
      - HIPAA
      - SOC2
    audit:
      interval: 24h
      retention: 7y
