apiVersion: security.orchestratex.com/v1
kind: SecurityPolicies
metadata:
  name: orchestratex-security-policies
  namespace: orchestratex
spec:
  policies:
    - name: quantum-encryption
      description: "Encryption policy for quantum operations"
      rules:
        - type: encryption
          algorithm: "kyber"
          key_length: 256
          mode: "gcm"
          requirements:
            - "Must use quantum-safe encryption"
            - "Minimum key length: 256 bits"
            - "Must use authenticated encryption"
      enforcement:
        enabled: true
        severity: critical
        action: block

    - name: quantum-authentication
      description: "Authentication policy for quantum access"
      rules:
        - type: authentication
          method: "jwt"
          algorithm: "dilithium"
          token_lifetime: "24h"
          requirements:
            - "Must use quantum-safe signatures"
            - "Token must expire within 24 hours"
            - "Must verify user identity"
      enforcement:
        enabled: true
        severity: critical
        action: block

    - name: quantum-access-control
      description: "Access control policy for quantum resources"
      rules:
        - type: authorization
          roles:
            - admin
            - quantum_engineer
            - researcher
          permissions:
            - "quantum:execute"
            - "quantum:state"
            - "quantum:circuit"
          requirements:
            - "Must verify user role"
            - "Must check resource permissions"
            - "Must enforce RBAC"
      enforcement:
        enabled: true
        severity: critical
        action: block

    - name: quantum-audit-logging
      description: "Audit logging policy for quantum operations"
      rules:
        - type: logging
          level: "info"
          retention: "30d"
          fields:
            - user_id
            - operation_type
            - timestamp
            - status
            - resource_id
          requirements:
            - "Must log all quantum operations"
            - "Must maintain logs for 30 days"
            - "Must include security-relevant fields"
      enforcement:
        enabled: true
        severity: warning
        action: log

    - name: quantum-rate-limiting
      description: "Rate limiting policy for quantum operations"
      rules:
        - type: rate_limit
          limit: "100r/s"
          window: "1m"
          burst: 200
          requirements:
            - "Must limit request rate"
            - "Must prevent abuse"
            - "Must handle bursts"
      enforcement:
        enabled: true
        severity: warning
        action: throttle

    - name: quantum-data-protection
      description: "Data protection policy for quantum operations"
      rules:
        - type: data_protection
          classification: "confidential"
          retention: "7d"
          backup: "daily"
          requirements:
            - "Must classify sensitive data"
            - "Must implement data retention"
            - "Must have regular backups"
      enforcement:
        enabled: true
        severity: critical
        action: block

  metrics:
    - name: encryption_coverage
      description: "Percentage of encrypted quantum operations"
      threshold: 100
      severity: critical
      alert: true

    - name: authentication_coverage
      description: "Percentage of authenticated quantum operations"
      threshold: 100
      severity: critical
      alert: true

    - name: authorization_coverage
      description: "Percentage of authorized quantum operations"
      threshold: 100
      severity: critical
      alert: true

    - name: audit_log_coverage
      description: "Percentage of audited quantum operations"
      threshold: 100
      severity: warning
      alert: true

    - name: rate_limit_coverage
      description: "Percentage of rate-limited quantum operations"
      threshold: 95
      severity: warning
      alert: true

    - name: data_protection_coverage
      description: "Percentage of protected quantum data"
      threshold: 100
      severity: critical
      alert: true

  alerts:
    - name: security_violation
      description: "Security policy violation detected"
      severity: critical
      notification_channels:
        - type: slack
          webhook: ${SLACK_WEBHOOK}
          channel: "#security"
        - type: email
          recipients:
            - "security@orchestratex.com"
            - "ops@orchestratex.com"

    - name: security_warning
      description: "Security warning threshold exceeded"
      severity: warning
      notification_channels:
        - type: slack
          webhook: ${SLACK_WEBHOOK}
          channel: "#alerts"
        - type: email
          recipients:
            - "ops@orchestratex.com"

  compliance:
    - standard: "NIST"
      requirements:
        - "Must implement quantum-safe cryptography"
        - "Must maintain audit logs"
        - "Must enforce access control"
    - standard: "ISO 27001"
      requirements:
        - "Must implement security policies"
        - "Must maintain security controls"
        - "Must conduct regular audits"

  monitoring:
    enabled: true
    interval: "1m"
    metrics:
      - name: policy_violations
        unit: "count"
        aggregation: "sum"
      - name: security_coverage
        unit: "%"
        aggregation: "avg"
      - name: alert_rate
        unit: "rate"
        aggregation: "rate"

  enforcement:
    enabled: true
    mode: strict
    exceptions:
      - name: development_env
        description: "Development environment exception"
        conditions:
          - environment: "dev"
          - severity: "warning"
      - name: maintenance_mode
        description: "Maintenance mode exception"
        conditions:
          - maintenance: true
          - severity: "critical"

  logging:
    enabled: true
    level: "info"
    format: "json"
    retention: "30d"
    fields:
      - timestamp
      - policy_name
      - resource
      - action
      - status
      - duration
      - user_id

  audit:
    enabled: true
    frequency: "daily"
    retention: "90d"
    report_format: "pdf"
    notification_channels:
      - type: email
        recipients:
          - "audit@orchestratex.com"
          - "compliance@orchestratex.com"
