apiVersion: monitoring.orchestratex.com/v1
kind: MonitoringConfig
metadata:
  name: orchestratex-monitoring
  namespace: orchestratex
spec:
  metrics:
    enabled: true
    collection:
      interval: "30s"
      retention:
        days: 30
        compression: true
        encryption: true
    providers:
      - name: prometheus
        url: "http://prometheus.orchestratex.svc.cluster.local:9090"
        scrape_interval: "15s"
        scrape_timeout: "10s"
      - name: grafana
        url: "http://grafana.orchestratex.svc.cluster.local:3000"
        dashboard_refresh: "30s"
    metrics:
      - name: quantum_error_rate
        description: "Quantum operation error rate"
        unit: "%"
        aggregation: "avg"
        threshold:
          warning: 0.5
          critical: 1.0
      - name: quantum_circuit_depth
        description: "Average quantum circuit depth"
        unit: "qubits"
        aggregation: "avg"
        threshold:
          warning: 100
          critical: 200
      - name: resource_utilization
        description: "Resource utilization percentage"
        unit: "%"
        aggregation: "avg"
        threshold:
          warning: 85
          critical: 90
      - name: request_latency
        description: "API request latency"
        unit: "ms"
        aggregation: "avg"
        threshold:
          warning: 500
          critical: 1000
      - name: error_rate
        description: "API error rate"
        unit: "%"
        aggregation: "avg"
        threshold:
          warning: 1.0
          critical: 2.0
  tracing:
    enabled: true
    provider: "jaeger"
    config:
      sampler:
        type: "probabilistic"
        param: 0.001
      reporter:
        batch_size: 100
        flush_interval: "1s"
      agent:
        host: "jaeger-agent.orchestratex.svc.cluster.local"
        port: 6831
    spans:
      - name: quantum_operation
        tags:
          - operation_type
          - quantum_state
          - circuit_depth
          - execution_time
      - name: api_request
        tags:
          - endpoint
          - method
          - status_code
          - duration
      - name: database_operation
        tags:
          - operation_type
          - table
          - duration
          - success
  alerts:
    enabled: true
    rules:
      - name: high_error_rate
        description: "High error rate detected"
        severity: critical
        threshold: 1.0
        duration: "5m"
        notification_channels:
          - type: slack
            webhook: ${SLACK_WEBHOOK}
            channel: "#alerts"
          - type: pagerduty
            service_key: ${PAGERDUTY_SERVICE_KEY}
      - name: resource_exhaustion
        description: "Resource utilization too high"
        severity: warning
        threshold: 85
        duration: "10m"
        notification_channels:
          - type: slack
            webhook: ${SLACK_WEBHOOK}
            channel: "#alerts"
          - type: email
            recipients:
              - "ops@orchestratex.com"
      - name: quantum_circuit_depth
        description: "Quantum circuit depth too high"
        severity: warning
        threshold: 100
        duration: "5m"
        notification_channels:
          - type: slack
            webhook: ${SLACK_WEBHOOK}
            channel: "#quantum"
          - type: email
            recipients:
              - "quantum@orchestratex.com"
    notification_channels:
      slack:
        webhook: ${SLACK_WEBHOOK}
        channel: "#alerts"
        severity:
          warning: true
          critical: true
      email:
        recipients:
          - "ops@orchestratex.com"
          - "security@orchestratex.com"
        severity:
          warning: true
          critical: true
      pagerduty:
        service_key: ${PAGERDUTY_SERVICE_KEY}
        severity:
          warning: false
          critical: true
  dashboards:
    enabled: true
    provider: "grafana"
    dashboards:
      - name: quantum_operations
        panels:
          - name: quantum_error_rate
            type: "timeseries"
            unit: "%"
            thresholds:
              warning: 0.5
              critical: 1.0
          - name: circuit_depth
            type: "timeseries"
            unit: "qubits"
            thresholds:
              warning: 100
              critical: 200
          - name: resource_utilization
            type: "timeseries"
            unit: "%"
            thresholds:
              warning: 85
              critical: 90
      - name: api_performance
        panels:
          - name: request_latency
            type: "timeseries"
            unit: "ms"
            thresholds:
              warning: 500
              critical: 1000
          - name: error_rate
            type: "timeseries"
            unit: "%"
            thresholds:
              warning: 1.0
              critical: 2.0
          - name: request_distribution
            type: "heatmap"
            unit: "requests"
      - name: system_health
        panels:
          - name: cpu_usage
            type: "timeseries"
            unit: "%"
            thresholds:
              warning: 85
              critical: 95
          - name: memory_usage
            type: "timeseries"
            unit: "%"
            thresholds:
              warning: 85
              critical: 95
          - name: disk_usage
            type: "timeseries"
            unit: "%"
            thresholds:
              warning: 85
              critical: 95
  tracing:
    enabled: true
    provider: "jaeger"
    config:
      sampler:
        type: "probabilistic"
        param: 0.001
      reporter:
        batch_size: 100
        flush_interval: "1s"
      agent:
        host: "jaeger-agent.orchestratex.svc.cluster.local"
        port: 6831
    spans:
      - name: quantum_operation
        tags:
          - operation_type
          - quantum_state
          - circuit_depth
          - execution_time
      - name: api_request
        tags:
          - endpoint
          - method
          - status_code
          - duration
      - name: database_operation
        tags:
          - operation_type
          - table
          - duration
          - success
  logging:
    enabled: true
    format: "json"
    level: "info"
    retention:
      days: 30
      compression: true
      encryption: true
    storage:
      type: "s3"
      bucket: "orchestratex-logs"
      region: "us-east-1"
    loggers:
      - name: quantum
        level: "debug"
        tags:
          - operation
          - circuit
          - state
      - name: api
        level: "info"
        tags:
          - endpoint
          - method
          - status
      - name: system
        level: "info"
        tags:
          - component
          - operation
          - status
  alert_manager:
    enabled: true
    config:
      global:
        resolve_timeout: "5m"
      route:
        group_by: ["alertname"]
        group_wait: "30s"
        group_interval: "5m"
        repeat_interval: "12h"
        receiver: "default"
      receivers:
        - name: "default"
          slack_configs:
            - api_url: ${SLACK_WEBHOOK}
              channel: "#alerts"
          email_configs:
            - to: "ops@orchestratex.com"
          pagerduty_configs:
            - service_key: ${PAGERDUTY_SERVICE_KEY}
  documentation:
    enabled: true
    format: "markdown"
    output_dir: "docs/monitoring"
    include:
      - "metrics_guide.md"
      - "alerts_guide.md"
      - "troubleshooting.md"
    exclude:
      - "**/draft_*.md"
      - "**/temp_*.md"
  compliance:
    enabled: true
    standards:
      - name: NIST 800-53
        requirements:
          - "AU-2 Audit Events"
          - "AU-3 Content of Audit Records"
          - "AU-4 Audit Storage"
          - "AU-6 Audit Review"
      - name: ISO 27001
        requirements:
          - "A.12.4.1 Audit trails"
          - "A.12.4.2 Protection of audit trails"
          - "A.12.4.3 Review of audit trails"
    exceptions:
      - name: development_environment
        description: "Development environment exception"
        conditions:
          - environment: "dev"
          - threshold: "warning"
      - name: experimental_code
        description: "Experimental code exception"
        conditions:
          - tag: "experimental"
          - threshold: "warning"
  audit:
    enabled: true
    retention:
      days: 365
      compression: true
      encryption: true
    storage:
      type: "s3"
      bucket: "orchestratex-audit"
      region: "us-east-1"
  alert_log:
    enabled: true
    retention:
      days: 365
      compression: true
      encryption: true
    storage:
      type: "s3"
      bucket: "orchestratex-alerts"
      region: "us-east-1"
  compliance_log:
    enabled: true
    retention:
      days: 365
      compression: true
      encryption: true
    storage:
      type: "s3"
      bucket: "orchestratex-compliance"
      region: "us-east-1"
