apiVersion: loadtesting.k8s.io/v1
kind: LoadTest
metadata:
  name: orchestratex-load-test
  namespace: orchestratex
spec:
  target:
    url: "https://api.orchestratex.com"
    endpoints:
      - path: "/quantum/circuit"
        method: "POST"
        headers:
          Content-Type: "application/json"
          Authorization: "Bearer ${TOKEN}"
      - path: "/quantum/state"
        method: "GET"
        headers:
          Authorization: "Bearer ${TOKEN}"
  scenarios:
    - name: "quantum-circuit-execution"
      duration: "30m"
      rampUp: "5m"
      rampDown: "5m"
      users:
        min: 100
        max: 1000
      requestsPerSecond: 100
      thinkTime: "1s"
      assertions:
        - metric: "response_time"
          threshold: "1s"
          comparison: "lt"
        - metric: "error_rate"
          threshold: "1%"
          comparison: "lt"
    - name: "quantum-state-query"
      duration: "30m"
      rampUp: "5m"
      rampDown: "5m"
      users:
        min: 50
        max: 500
      requestsPerSecond: 50
      thinkTime: "500ms"
      assertions:
        - metric: "response_time"
          threshold: "500ms"
          comparison: "lt"
        - metric: "error_rate"
          threshold: "0.5%"
          comparison: "lt"
  metrics:
    - name: "response_time"
      unit: "ms"
      aggregation: "avg"
    - name: "error_rate"
      unit: "%"
      aggregation: "avg"
    - name: "throughput"
      unit: "req/s"
      aggregation: "sum"
  monitoring:
    enabled: true
    interval: "1s"
    metrics:
      - name: "cpu_usage"
        unit: "%"
        threshold: "80%"
      - name: "memory_usage"
        unit: "MB"
        threshold: "1024MB"
      - name: "network_latency"
        unit: "ms"
        threshold: "100ms"
  notifications:
    enabled: true
    providers:
      - type: "slack"
        webhook: "${SLACK_WEBHOOK}"
        channel: "#load-testing"
      - type: "email"
        recipients:
          - "ops@orchestratex.com"
          - "dev@orchestratex.com"
  dataGeneration:
    enabled: true
    templates:
      - name: "quantum-circuit"
        type: "json"
        size: "1KB"
        complexity: "high"
      - name: "quantum-state"
        type: "json"
        size: "512B"
        complexity: "medium"
  validation:
    enabled: true
    rules:
      - name: "response_validation"
        type: "json_schema"
        schema: |
          {
            "type": "object",
            "required": ["status", "result"],
            "properties": {
              "status": {"type": "string"},
              "result": {"type": "object"}
            }
          }
      - name: "performance_validation"
        type: "threshold"
        thresholds:
          response_time: "1s"
          error_rate: "1%"
          throughput: "100req/s"
